packages:
  - .
overrides:
  'source-map-js@<1.2.2': '1.2.2'
  'proxy-addr@<2.0.8': '2.0.8'
  'tinypool@<2.1.2': '2.1.2'
  'node-fetch@<2.6.7': '2.7.0'
  jayson: '5.0.0'
  toml: '4.2.0'
  'fast-uri@>=3.0.0 <3.1.8': '3.1.8'
  'ip-address@>=10.0.0 <10.7.1': '10.7.1'
  'brace-expansion@>=5.0.0 <5.0.12': '5.0.12'
  'react': '19.2.8'
  'react-dom': '19.2.8'
  'react-server-dom-webpack': '19.2.8'
  'ws@>=8.0.0 <8.21.0': '8.21.0'
  'undici@>=7.0.0 <7.29.1': '7.29.1'
  'sharp@<0.35.4': '0.35.4'
  'esbuild@<=0.24.2': '0.25.12'
  'esbuild@0.27.3': '0.28.1'
  'vinext>image-size': '-'
packageExtensions:
  'vinext@1.0.0-beta.5':
    dependencies:
      image-dimensions: '2.5.1'
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
patchedDependencies:
  braces@3.0.3: patches/braces@3.0.3.patch
  vinext@1.0.0-beta.5: patches/vinext@1.0.0-beta.5.patch
