packages:
  - .
overrides:
  'react': '19.2.8'
  'react-dom': '19.2.8'
  'react-server-dom-webpack': '19.2.8'
  'ws@>=8.0.0 <8.21.0': '8.21.0'
  'undici@>=7.0.0 <7.29.0': '7.29.0'
  'sharp@<0.35.4': '0.35.4'
  'esbuild@<=0.24.2': '0.25.12'
  'esbuild@0.27.3': '0.28.1'
  'vinext>image-size': '-'
packageExtensions:
  'vinext@1.0.0-beta.5':
    dependencies:
      image-dimensions: '2.5.1'
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
patchedDependencies:
  vinext@1.0.0-beta.5: patches/vinext@1.0.0-beta.5.patch
